# permissions for end users to view ssanginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssanginx-viewer-role
rules:
- apiGroups:
  - ssanginx.jnytnai0613.github.io
  resources:
  - ssanginxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ssanginx.jnytnai0613.github.io
  resources:
  - ssanginxes/status
  verbs:
  - get
