# permissions for end users to edit ssanginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssanginx-editor-role
rules:
- apiGroups:
  - ssanginx.jnytnai0613.github.io
  resources:
  - ssanginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ssanginx.jnytnai0613.github.io
  resources:
  - ssanginxes/status
  verbs:
  - get
