name: main
on:
  pull_request:
  push:
    branches:
      - 'test'

jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install gcc
      - run: make test
